language: ruby
sudo: false
rvm:
  - 1.8.7
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.1.5.0
  - rbx
  - rbx-2
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-9.1.5.0
    - rvm: rbx
    - rvm: rbx-2